import { useEffect } from 'react'
import { Controller, useFieldArray, type UseFormReturn } from 'react-hook-form'
import { useQuery } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldError, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { FormDate, FormMoney, FormSelect, FormText, FormTextarea } from '@/components/form/fields'
import { CustomerPicker } from '@/components/pickers/CustomerPicker'
import { ProductPicker } from '@/components/pickers/ProductPicker'
import { UserPicker } from '@/components/pickers/UserPicker'
import { AllocationsField } from '@/components/payments/AllocationsField'
import { customerDetailOptions } from '@/hooks/useCustomers'
import { CUSTOMER_TYPE_LABELS, DEAL_TYPE_LABELS } from '@/lib/labels'
import { EMPTY_LINE, type SalesFormValues } from './schema'
type Form=UseFormReturn<SalesFormValues>
const options=(v:Record<string,string>)=>Object.entries(v).map(([value,label])=>({value,label}))
function UserField({form,name,label,required=false}:{form:Form;name:'handler_user_id'|'expert_user_id'|'consultant_user_id'|'doctor_user_id';label:string;required?:boolean}){return <Controller control={form.control} name={name} render={({field,fieldState})=><Field data-invalid={fieldState.invalid||undefined}><FieldLabel>{label}{required&&' *'}</FieldLabel><UserPicker value={field.value||undefined} onChange={v=>field.onChange(v??'')}/>{fieldState.error&&<FieldError>{fieldState.error.message}</FieldError>}</Field>}/ >}
export function CustomerSection({form}:{form:Form}){const kind=form.watch('record_type');const customerId=form.watch('customer_id');const {data:customer}=useQuery({...customerDetailOptions(customerId),enabled:Boolean(customerId)});useEffect(()=>{form.setValue('customer_outstanding',customer?.outstanding_amount??'')},[customer?.outstanding_amount,form]);return <div className="grid gap-4 md:grid-cols-2"><Controller control={form.control} name="record_type" render={({field})=><Field className="md:col-span-2"><FieldLabel>记录类型 *</FieldLabel><Tabs value={field.value} onValueChange={v=>{field.onChange(v);if(v==='pre_service'){form.setValue('received_amount','0');form.setValue('allocations',[])}else if(!form.getValues('allocations').length){form.setValue('allocations',[{guide_user_id:'',allocation_ratio:'100'}])}if(v==='debt_collection')form.setValue('lines',[]);else if(!form.getValues('lines').length)form.setValue('lines',[{...EMPTY_LINE}])}}><TabsList><TabsTrigger value="deal">成交</TabsTrigger><TabsTrigger value="pre_service">铺垫+服务</TabsTrigger><TabsTrigger value="debt_collection">收欠款</TabsTrigger></TabsList></Tabs></Field>}/><Controller control={form.control} name="customer_id" render={({field,fieldState})=><Field data-invalid={fieldState.invalid||undefined}><FieldLabel>客户 *</FieldLabel><CustomerPicker value={field.value||undefined} onChange={v=>field.onChange(v??'')}/>{fieldState.error&&<FieldError>{fieldState.error.message}</FieldError>}</Field>}/><FormDate control={form.control} name="record_date" label="业务日期" required/>{kind==='debt_collection'&&<p className="text-sm text-muted-foreground md:col-span-2">当前欠款：¥{customer?.outstanding_amount??'0.00'}</p>}{kind!=='debt_collection'&&<><FormSelect control={form.control} name="customer_type" label="客户类型" options={options(CUSTOMER_TYPE_LABELS)} required/><FormSelect control={form.control} name="deal_type" label="成交类型" options={options(DEAL_TYPE_LABELS)} required/></>}</div>}
export function LinesSection({form}:{form:Form}){const kind=form.watch('record_type');const {fields,append,remove}=useFieldArray({control:form.control,name:'lines'});if(kind==='debt_collection')return null;const lines=form.watch('lines');return <div className="flex flex-col gap-3">{fields.map((f,i)=><Card key={f.id}><CardHeader><CardTitle>售出内容 {i+1}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><Controller control={form.control} name={`lines.${i}.product_id`} render={({field,fieldState})=><Field data-invalid={fieldState.invalid||undefined}><FieldLabel>产品 *</FieldLabel><ProductPicker value={field.value||undefined} onChange={(id,p)=>{field.onChange(id??'');form.setValue(`lines.${i}.requires_operation_count`,p?.requires_operation_count??false);form.setValue(`lines.${i}.operation_total_count`,undefined);if(p)form.setValue(`lines.${i}.item_name`,p.name)}}/>{fieldState.error&&<FieldError>{fieldState.error.message}</FieldError>}</Field>}/><FormText control={form.control} name={`lines.${i}.item_name`} label="项目名称" required/>{lines[i]?.requires_operation_count&&<Controller control={form.control} name={`lines.${i}.operation_total_count`} render={({field,fieldState})=><Field><FieldLabel>可操作次数 *</FieldLabel><Input type="number" min={1} value={field.value??''} onChange={e=>field.onChange(e.target.value?Number(e.target.value):undefined)}/>{fieldState.error&&<FieldError>{fieldState.error.message}</FieldError>}</Field>}/>}<FormText control={form.control} name={`lines.${i}.remark`} label="备注"/>{fields.length>1&&<Button type="button" variant="ghost" onClick={()=>remove(i)}><Trash2/>删除</Button>}</CardContent></Card>)}<Button type="button" variant="outline" onClick={()=>append({...EMPTY_LINE})}><Plus/>添加售出内容</Button></div>}
export function PaymentSection({form}:{form:Form}){const kind=form.watch('record_type');const allocations=form.watch('allocations');const error=form.formState.errors.allocations?.message;return <div className="grid gap-4 md:grid-cols-2">{kind!=='debt_collection'&&<FormMoney control={form.control} name="total_amount" label="销售总价" required/>}{kind!=='pre_service'&&<FormMoney control={form.control} name="received_amount" label={kind==='deal'?'本次实收':'收欠款金额'} required/>}<UserField form={form} name="handler_user_id" label="处理人" required/><UserField form={form} name="expert_user_id" label="专家"/><UserField form={form} name="consultant_user_id" label="顾问"/><UserField form={form} name="doctor_user_id" label="医生"/><FormTextarea control={form.control} name="remark" label="备注" className="md:col-span-2"/>{kind!=='pre_service'&&<div className="md:col-span-2"><AllocationsField control={form.control} name="allocations" rows={allocations} error={typeof error==='string'?error:undefined}/></div>}</div>}
