[server]
bind_addr = "127.0.0.1:3000"

[database]
kind = "postgres"
url = "postgres://postgres:postgres@localhost:5432/atlas"
sqlite_file = "data/atlas.sqlite"

[dingtalk]
client_id = "dingqvfuxtyfxaisavfd"
client_secret = "OSMaCRzHIoPICS0g8uVnE4USEdOaVZUDGc6ocO9p8XM76z4wlA3CwQv7uf17LDGJ"
redirect_uri = "http://127.0.0.1:3000/api/v1/auth/callback/dingtalk"
auth_url = "https://login.dingtalk.com/oauth2/auth"
token_url = "https://api.dingtalk.com/v1.0/oauth2/userAccessToken"
user_info_url = "https://api.dingtalk.com/v1.0/contact/users/me"
corp_token_url = "https://oapi.dingtalk.com/gettoken"
department_listsub_url = "https://oapi.dingtalk.com/topapi/v2/department/listsub"
user_detail_url = "https://oapi.dingtalk.com/topapi/v2/user/get"
scope = "openid corpid"
corp_id = "ding2e18483b8101064935c2f4657eb6378f"
external_id_fields = ["userId", "userid", "user_id", "unionId", "unionid", "union_id", "openId", "openid", "open_id", "uuid"]

[auth]
frontend_callback_url = ""

[session]
ttl_seconds = 86400
cookie_secure = false
