/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppManageRouteImport } from './routes/_app/manage'
import { Route as App403RouteImport } from './routes/_app/403'
import { Route as AppUsagesIndexRouteImport } from './routes/_app/usages/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCountsIndexRouteImport } from './routes/_app/counts/index'
import { Route as AppApprovalsIndexRouteImport } from './routes/_app/approvals/index'
import { Route as AppUsagesNewRouteImport } from './routes/_app/usages/new'
import { Route as AppSalesNewRouteImport } from './routes/_app/sales/new'
import { Route as AppReportsReportIdRouteImport } from './routes/_app/reports/$reportId'
import { Route as AppOrgSystemsRouteImport } from './routes/_app/org/systems'
import { Route as AppOrgStoresRouteImport } from './routes/_app/org/stores'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers/new'
import { Route as AppApprovalsEventIdRouteImport } from './routes/_app/approvals/$eventId'
import { Route as AppAdminDepartmentsRouteImport } from './routes/_app/admin/departments'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppSalesSalesIdIndexRouteImport } from './routes/_app/sales/$salesId/index'
import { Route as AppCustomersCustomerIdIndexRouteImport } from './routes/_app/customers/$customerId/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminPermissionsIndexRouteImport } from './routes/_app/admin/permissions/index'
import { Route as AppCustomersCustomerIdEditRouteImport } from './routes/_app/customers/$customerId/edit'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminPermissionsRolesRoleIdRouteImport } from './routes/_app/admin/permissions/roles/$roleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const App403Route = App403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AppRoute,
} as any)
const AppUsagesIndexRoute = AppUsagesIndexRouteImport.update({
  id: '/usages/',
  path: '/usages/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCountsIndexRoute = AppCountsIndexRouteImport.update({
  id: '/counts/',
  path: '/counts/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsagesNewRoute = AppUsagesNewRouteImport.update({
  id: '/usages/new',
  path: '/usages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSystemsRoute = AppOrgSystemsRouteImport.update({
  id: '/org/systems',
  path: '/org/systems',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgStoresRoute = AppOrgStoresRouteImport.update({
  id: '/org/stores',
  path: '/org/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsEventIdRoute = AppApprovalsEventIdRouteImport.update({
  id: '/approvals/$eventId',
  path: '/approvals/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesSalesIdIndexRoute = AppSalesSalesIdIndexRouteImport.update({
  id: '/sales/$salesId/',
  path: '/sales/$salesId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdIndexRoute =
  AppCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissionsIndexRoute =
  AppAdminPermissionsIndexRouteImport.update({
    id: '/admin/permissions/',
    path: '/admin/permissions/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdEditRoute =
  AppCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissionsRolesRoleIdRoute =
  AppAdminPermissionsRolesRoleIdRouteImport.update({
    id: '/admin/permissions/roles/$roleId',
    path: '/admin/permissions/roles/$roleId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/403': typeof App403Route
  '/manage': typeof AppManageRoute
  '/me': typeof AppMeRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/approvals/$eventId': typeof AppApprovalsEventIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/org/stores': typeof AppOrgStoresRoute
  '/org/systems': typeof AppOrgSystemsRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/sales/new': typeof AppSalesNewRoute
  '/usages/new': typeof AppUsagesNewRoute
  '/approvals/': typeof AppApprovalsIndexRoute
  '/counts/': typeof AppCountsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/usages/': typeof AppUsagesIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/admin/permissions/': typeof AppAdminPermissionsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/sales/$salesId/': typeof AppSalesSalesIdIndexRoute
  '/admin/permissions/roles/$roleId': typeof AppAdminPermissionsRolesRoleIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/403': typeof App403Route
  '/manage': typeof AppManageRoute
  '/me': typeof AppMeRoute
  '/': typeof AppIndexRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/approvals/$eventId': typeof AppApprovalsEventIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/org/stores': typeof AppOrgStoresRoute
  '/org/systems': typeof AppOrgSystemsRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/sales/new': typeof AppSalesNewRoute
  '/usages/new': typeof AppUsagesNewRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/counts': typeof AppCountsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/usages': typeof AppUsagesIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/admin/permissions': typeof AppAdminPermissionsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdIndexRoute
  '/sales/$salesId': typeof AppSalesSalesIdIndexRoute
  '/admin/permissions/roles/$roleId': typeof AppAdminPermissionsRolesRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/403': typeof App403Route
  '/_app/manage': typeof AppManageRoute
  '/_app/me': typeof AppMeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/departments': typeof AppAdminDepartmentsRoute
  '/_app/approvals/$eventId': typeof AppApprovalsEventIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/org/stores': typeof AppOrgStoresRoute
  '/_app/org/systems': typeof AppOrgSystemsRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/usages/new': typeof AppUsagesNewRoute
  '/_app/approvals/': typeof AppApprovalsIndexRoute
  '/_app/counts/': typeof AppCountsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/usages/': typeof AppUsagesIndexRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/customers/$customerId/edit': typeof AppCustomersCustomerIdEditRoute
  '/_app/admin/permissions/': typeof AppAdminPermissionsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/_app/sales/$salesId/': typeof AppSalesSalesIdIndexRoute
  '/_app/admin/permissions/roles/$roleId': typeof AppAdminPermissionsRolesRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/403'
    | '/manage'
    | '/me'
    | '/admin/audit'
    | '/admin/departments'
    | '/approvals/$eventId'
    | '/customers/new'
    | '/org/stores'
    | '/org/systems'
    | '/reports/$reportId'
    | '/sales/new'
    | '/usages/new'
    | '/approvals/'
    | '/counts/'
    | '/customers/'
    | '/payments/'
    | '/products/'
    | '/sales/'
    | '/usages/'
    | '/admin/users/$userId'
    | '/customers/$customerId/edit'
    | '/admin/permissions/'
    | '/admin/users/'
    | '/customers/$customerId/'
    | '/sales/$salesId/'
    | '/admin/permissions/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/403'
    | '/manage'
    | '/me'
    | '/'
    | '/admin/audit'
    | '/admin/departments'
    | '/approvals/$eventId'
    | '/customers/new'
    | '/org/stores'
    | '/org/systems'
    | '/reports/$reportId'
    | '/sales/new'
    | '/usages/new'
    | '/approvals'
    | '/counts'
    | '/customers'
    | '/payments'
    | '/products'
    | '/sales'
    | '/usages'
    | '/admin/users/$userId'
    | '/customers/$customerId/edit'
    | '/admin/permissions'
    | '/admin/users'
    | '/customers/$customerId'
    | '/sales/$salesId'
    | '/admin/permissions/roles/$roleId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/403'
    | '/_app/manage'
    | '/_app/me'
    | '/_app/'
    | '/_app/admin/audit'
    | '/_app/admin/departments'
    | '/_app/approvals/$eventId'
    | '/_app/customers/new'
    | '/_app/org/stores'
    | '/_app/org/systems'
    | '/_app/reports/$reportId'
    | '/_app/sales/new'
    | '/_app/usages/new'
    | '/_app/approvals/'
    | '/_app/counts/'
    | '/_app/customers/'
    | '/_app/payments/'
    | '/_app/products/'
    | '/_app/sales/'
    | '/_app/usages/'
    | '/_app/admin/users/$userId'
    | '/_app/customers/$customerId/edit'
    | '/_app/admin/permissions/'
    | '/_app/admin/users/'
    | '/_app/customers/$customerId/'
    | '/_app/sales/$salesId/'
    | '/_app/admin/permissions/roles/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/403': {
      id: '/_app/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof App403RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usages/': {
      id: '/_app/usages/'
      path: '/usages'
      fullPath: '/usages/'
      preLoaderRoute: typeof AppUsagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/counts/': {
      id: '/_app/counts/'
      path: '/counts'
      fullPath: '/counts/'
      preLoaderRoute: typeof AppCountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/': {
      id: '/_app/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usages/new': {
      id: '/_app/usages/new'
      path: '/usages/new'
      fullPath: '/usages/new'
      preLoaderRoute: typeof AppUsagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/systems': {
      id: '/_app/org/systems'
      path: '/org/systems'
      fullPath: '/org/systems'
      preLoaderRoute: typeof AppOrgSystemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/stores': {
      id: '/_app/org/stores'
      path: '/org/stores'
      fullPath: '/org/stores'
      preLoaderRoute: typeof AppOrgStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/$eventId': {
      id: '/_app/approvals/$eventId'
      path: '/approvals/$eventId'
      fullPath: '/approvals/$eventId'
      preLoaderRoute: typeof AppApprovalsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/departments': {
      id: '/_app/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$salesId/': {
      id: '/_app/sales/$salesId/'
      path: '/sales/$salesId'
      fullPath: '/sales/$salesId/'
      preLoaderRoute: typeof AppSalesSalesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId/': {
      id: '/_app/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AppCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions/': {
      id: '/_app/admin/permissions/'
      path: '/admin/permissions'
      fullPath: '/admin/permissions/'
      preLoaderRoute: typeof AppAdminPermissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId/edit': {
      id: '/_app/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AppCustomersCustomerIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions/roles/$roleId': {
      id: '/_app/admin/permissions/roles/$roleId'
      path: '/admin/permissions/roles/$roleId'
      fullPath: '/admin/permissions/roles/$roleId'
      preLoaderRoute: typeof AppAdminPermissionsRolesRoleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  App403Route: typeof App403Route
  AppManageRoute: typeof AppManageRoute
  AppMeRoute: typeof AppMeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppApprovalsEventIdRoute: typeof AppApprovalsEventIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppOrgStoresRoute: typeof AppOrgStoresRoute
  AppOrgSystemsRoute: typeof AppOrgSystemsRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppUsagesNewRoute: typeof AppUsagesNewRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppCountsIndexRoute: typeof AppCountsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppUsagesIndexRoute: typeof AppUsagesIndexRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppCustomersCustomerIdEditRoute: typeof AppCustomersCustomerIdEditRoute
  AppAdminPermissionsIndexRoute: typeof AppAdminPermissionsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppCustomersCustomerIdIndexRoute: typeof AppCustomersCustomerIdIndexRoute
  AppSalesSalesIdIndexRoute: typeof AppSalesSalesIdIndexRoute
  AppAdminPermissionsRolesRoleIdRoute: typeof AppAdminPermissionsRolesRoleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  App403Route: App403Route,
  AppManageRoute: AppManageRoute,
  AppMeRoute: AppMeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppApprovalsEventIdRoute: AppApprovalsEventIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppOrgStoresRoute: AppOrgStoresRoute,
  AppOrgSystemsRoute: AppOrgSystemsRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppUsagesNewRoute: AppUsagesNewRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppCountsIndexRoute: AppCountsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppUsagesIndexRoute: AppUsagesIndexRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppCustomersCustomerIdEditRoute: AppCustomersCustomerIdEditRoute,
  AppAdminPermissionsIndexRoute: AppAdminPermissionsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppCustomersCustomerIdIndexRoute: AppCustomersCustomerIdIndexRoute,
  AppSalesSalesIdIndexRoute: AppSalesSalesIdIndexRoute,
  AppAdminPermissionsRolesRoleIdRoute: AppAdminPermissionsRolesRoleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
